POST http://127.0.0.1:5000/prever
Content-Type: application/json

{
  "ocasião": "Casual, Dia a Dia",
  "periodo": "Todo o Ano",
  "clima": "Quente",
  "sexo": "Masculino",
  "sentimento": "Fresco, Leve",
  "notas": "Almíscar, Notas amadeiradas",
  "estilo": "Jovem, Natural",
  "faixa_etaria": "18-35"
}